// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhm-ObizjRpwIHuDnptYQXPIpaZM5F-dI',
    appId: '1:126567893525:web:f514a7e30e562eb9f05c1c',
    messagingSenderId: '126567893525',
    projectId: 'flutter-firbase-b7c74',
    authDomain: 'flutter-firbase-b7c74.firebaseapp.com',
    storageBucket: 'flutter-firbase-b7c74.appspot.com',
    measurementId: 'G-5QL6ZZEZQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf1X37PAentdvljyI4WHurAZomp0rlSXk',
    appId: '1:126567893525:android:318064858a7a6491f05c1c',
    messagingSenderId: '126567893525',
    projectId: 'flutter-firbase-b7c74',
    storageBucket: 'flutter-firbase-b7c74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1-lPRfzLMELnbV4mSGZOzPek82GTG4c',
    appId: '1:126567893525:ios:aa0bb28d77f0f6d3f05c1c',
    messagingSenderId: '126567893525',
    projectId: 'flutter-firbase-b7c74',
    storageBucket: 'flutter-firbase-b7c74.appspot.com',
    iosBundleId: 'com.example.firebaseauthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM1-lPRfzLMELnbV4mSGZOzPek82GTG4c',
    appId: '1:126567893525:ios:d3b3df2cfe115c71f05c1c',
    messagingSenderId: '126567893525',
    projectId: 'flutter-firbase-b7c74',
    storageBucket: 'flutter-firbase-b7c74.appspot.com',
    iosBundleId: 'com.example.firebaseauthentication.RunnerTests',
  );
}
